### ISSUE TITLE
$ sudo chown -R $USER /usr/share/xessions

### ISSUE THREAD

**Issue by drmarwat** [sammi-turner/Snazzy-Window-Manager#1]
I am giving a try to your WM but the suggested command by you gives me error
chown: cannot access '/usr/share/xessions': No such file or directory  even that I have /usr/share/xsessions on my installation , so I am leaving this command not to be executed for a while

**Comment by sammi-turner** [comment]
That error is caused by not having running the command without root access. Use sudo or log in as root.
