### ISSUE TITLE
picom error

### ISSUE THREAD

**Issue by drmarwat** [sammi-turner/Snazzy-Window-Manager#2]
picom did not start from startup file and running it from terminal I get this error

picom
[ 10/01/2020 00:38:20.089 parse_config_libconfig FATAL ERROR ] Error when reading configuration file "/home/saleem/.config/picom/picom.conf", line 1: syntax error
[ 10/01/2020 00:38:20.089 main FATAL ERROR ] Failed to create new session.

Kindly help me debug this issue.

**Comment by drmarwat** [comment]
got it fixed , there was this line at the top of your file " ~/.config/picom/picom.conf " so I commented it out and now picom works 
#~/.config/picom/picom.conf

**Comment by sammi-turner** [comment]
I'm glad that you were able to find a fix :)
