### ISSUE TITLE
polybar

### ISSUE THREAD

**Issue by drmarwat** [sammi-turner/Snazzy-Window-Manager#3]
I would love to have a polybar on SWM . Can you make a dot file for it as well?

**Comment by drmarwat** [comment]
for ploybar on dwm/swm ?this might be of help
https://github.com/mihirlad55/polybar-dwm-module

**Comment by sammi-turner** [comment]
That would be a nice feature!

If you would like to implement the desired changes on your system and make a pull request, then I'd be very happy to take a look at them and consider merging the changes :)
