### ISSUE TITLE
rofi

### ISSUE THREAD

**Issue by drmarwat** [sammi-turner/Snazzy-Window-Manager#4]
Would you consider making a rofi dot as well please?

**Comment by sammi-turner** [comment]
Ah that would be a good feature!

If you have an existing rofi config, feel free to make a pull request and I'll have a look.

**Comment by drmarwat** [comment]
I am reading and searching : found this link of how to make rofi work on dwm/swm
https://www.reddit.com/r/suckless/comments/gs7fjz/how_do_i_add_rofi_show_drun_showicons_to_dwm/fs454c9/
Will post back if I get successful in getting rofi on SWM
