### ISSUE TITLE
alt key as mod key

### ISSUE THREAD

**Issue by drmarwat** [sammi-turner/Snazzy-Window-Manager#5]
What if I want to change Mod key from alt to windows key , do I have to recompile SWM once again? and what changes do I have to make in config.h file to set mod key to windows key before recompiling?

**Comment by sammi-turner** [comment]
"What if I want to change Mod key from alt to windows key, do I have to recompile SWM once again?"

Yes, that requires recompilation, logging out and back in again. Same as with DWM.

"what changes do I have to make in config.h file to set mod key to windows key before recompiling?"

First, I would check that this doesn't clash with any existing keybinds in your sxhkdrc file or any other programs that you might be using.

But the simple x hotkey daemon changes don't require recompilation. Just a save and refresh.

In config.h, 'mod1' refers to alt and 'mod4' refers to the super (windows) key.

In sxhkdrc, you can use the names 'alt' and 'super'.
