### ISSUE TITLE
battery monitoring

### ISSUE THREAD

**Issue by drmarwat** [sammi-turner/Snazzy-Window-Manager#6]
SWM is lacking battery charge level display in top bar . How to get a visual of available battery percentage available ?

**Comment by sammi-turner** [comment]
That feature could be added in two ways.

1. By adding new code to the autostart shell script.
2. By using [DWM blocks](https://github.com/torrinfail/dwmblocks) instead of the default SWM bar.

**Comment by drmarwat** [comment]
As I am probing into each and every file so I am discovering things...missing packages on my system , so as soon as I installed acpi package my battery % appeared on the bar. I would suggest to include acpi in the needed packages list for others if you like to.

**Comment by drmarwat** [comment]
As I am probing into each and every file so I am discovering things...missing packages on my system , so as soon as I installed acpi package my battery % appeared on the bar. I would suggest to include acpi in the needed packages list for others if you like to.

**Comment by sammi-turner** [comment]
Oh excellent!

I will do that :)
