### ISSUE TITLE
Bar clock in AM PM ( 12 HOURS ) FORMAT

### ISSUE THREAD

**Issue by drmarwat** [sammi-turner/Snazzy-Window-Manager#7]
At this moment I am trying to figure out how to get 12 hours format in my clock. May be you can help me .

**Comment by drmarwat** [comment]
By the way I like my calendar and clock in this form
01-10-2020 02 PM 
Don`t know atm if this format can be achieved or not

**Comment by sammi-turner** [comment]
To switch to 12 hour time format, replace the two instances of '%R' with '%r' in your autostart.sh file.
