### ISSUE TITLE
exit, reboot,shutdown function

### ISSUE THREAD

**Issue by drmarwat** [sammi-turner/Snazzy-Window-Manager#8]
I dont know how you achieve it but I installed clearine and ctl + x in sxhkdrc makes it work like a charm

**Comment by sammi-turner** [comment]
Oh I'm glad that works well for you :)

Personally, I use a log in manager (the default one for EndeavourOS xfce edition) for that task.

As a back up, in my .bashrc file (see my pinned Linux dotfiles repo), I also have the following aliases.

# Start up with .xinitrc
alias sx='startx'

# Shut-down from terminal
alias sn='sudo shutdown now'

# Reboot from terminal
alias sr='sudo reboot'
